// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	user_svc "visual-state-machine/internal/api/user"
	user_logic "visual-state-machine/internal/logic/user"
	user_repo "visual-state-machine/internal/repo/user"
)

// InitApis 初始化所有API
func InitApis() *Apis {
	userApi := handleUserApi()
	return newApis(userApi)
}

func handleUserApi() *user_svc.Api {
	userRepo := user_repo.New()
	userLogic := user_logic.New(userRepo)
	userApi := user_svc.New(userLogic)
	return userApi
}
