// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.3
// source: cache-monitor.proto

package cache_monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCacheUserAddressListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
}

func (x *GetCacheUserAddressListRequest) Reset() {
	*x = GetCacheUserAddressListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserAddressListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserAddressListRequest) ProtoMessage() {}

func (x *GetCacheUserAddressListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserAddressListRequest.ProtoReflect.Descriptor instead.
func (*GetCacheUserAddressListRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *GetCacheUserAddressListRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type GetCacheUserAddressListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCacheAddressList []string `protobuf:"bytes,1,rep,name=UserCacheAddressList,proto3" json:"UserCacheAddressList,omitempty"`
}

func (x *GetCacheUserAddressListResponse) Reset() {
	*x = GetCacheUserAddressListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserAddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserAddressListResponse) ProtoMessage() {}

func (x *GetCacheUserAddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserAddressListResponse.ProtoReflect.Descriptor instead.
func (*GetCacheUserAddressListResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *GetCacheUserAddressListResponse) GetUserCacheAddressList() []string {
	if x != nil {
		return x.UserCacheAddressList
	}
	return nil
}

type GetCacheUserAppNameListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCacheUserAppNameListRequest) Reset() {
	*x = GetCacheUserAppNameListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserAppNameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserAppNameListRequest) ProtoMessage() {}

func (x *GetCacheUserAppNameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserAppNameListRequest.ProtoReflect.Descriptor instead.
func (*GetCacheUserAppNameListRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{2}
}

type GetCacheUserAppNameListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCacheAppNameList []string `protobuf:"bytes,1,rep,name=UserCacheAppNameList,proto3" json:"UserCacheAppNameList,omitempty"`
}

func (x *GetCacheUserAppNameListResponse) Reset() {
	*x = GetCacheUserAppNameListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserAppNameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserAppNameListResponse) ProtoMessage() {}

func (x *GetCacheUserAppNameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserAppNameListResponse.ProtoReflect.Descriptor instead.
func (*GetCacheUserAppNameListResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *GetCacheUserAppNameListResponse) GetUserCacheAppNameList() []string {
	if x != nil {
		return x.UserCacheAppNameList
	}
	return nil
}

type GetCacheNameListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCacheNameListRequest) Reset() {
	*x = GetCacheNameListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheNameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheNameListRequest) ProtoMessage() {}

func (x *GetCacheNameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheNameListRequest.ProtoReflect.Descriptor instead.
func (*GetCacheNameListRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{4}
}

type GetCacheNameListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheNameList []string `protobuf:"bytes,1,rep,name=CacheNameList,proto3" json:"CacheNameList,omitempty"`
}

func (x *GetCacheNameListResponse) Reset() {
	*x = GetCacheNameListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheNameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheNameListResponse) ProtoMessage() {}

func (x *GetCacheNameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheNameListResponse.ProtoReflect.Descriptor instead.
func (*GetCacheNameListResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *GetCacheNameListResponse) GetCacheNameList() []string {
	if x != nil {
		return x.CacheNameList
	}
	return nil
}

type GetCacheKeyListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheName string `protobuf:"bytes,1,opt,name=CacheName,proto3" json:"CacheName,omitempty"`
}

func (x *GetCacheKeyListRequest) Reset() {
	*x = GetCacheKeyListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheKeyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheKeyListRequest) ProtoMessage() {}

func (x *GetCacheKeyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheKeyListRequest.ProtoReflect.Descriptor instead.
func (*GetCacheKeyListRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *GetCacheKeyListRequest) GetCacheName() string {
	if x != nil {
		return x.CacheName
	}
	return ""
}

type GetCacheKeyListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheKeyList []string `protobuf:"bytes,1,rep,name=CacheKeyList,proto3" json:"CacheKeyList,omitempty"`
}

func (x *GetCacheKeyListResponse) Reset() {
	*x = GetCacheKeyListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheKeyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheKeyListResponse) ProtoMessage() {}

func (x *GetCacheKeyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheKeyListResponse.ProtoReflect.Descriptor instead.
func (*GetCacheKeyListResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *GetCacheKeyListResponse) GetCacheKeyList() []string {
	if x != nil {
		return x.CacheKeyList
	}
	return nil
}

type GetValueToCacheUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheName string `protobuf:"bytes,1,opt,name=CacheName,proto3" json:"CacheName,omitempty"`
	CacheKey  string `protobuf:"bytes,2,opt,name=CacheKey,proto3" json:"CacheKey,omitempty"`
}

func (x *GetValueToCacheUserRequest) Reset() {
	*x = GetValueToCacheUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValueToCacheUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueToCacheUserRequest) ProtoMessage() {}

func (x *GetValueToCacheUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueToCacheUserRequest.ProtoReflect.Descriptor instead.
func (*GetValueToCacheUserRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *GetValueToCacheUserRequest) GetCacheName() string {
	if x != nil {
		return x.CacheName
	}
	return ""
}

func (x *GetValueToCacheUserRequest) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

type GetValueToCacheUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheValue string `protobuf:"bytes,1,opt,name=CacheValue,proto3" json:"CacheValue,omitempty"`
}

func (x *GetValueToCacheUserResponse) Reset() {
	*x = GetValueToCacheUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValueToCacheUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueToCacheUserResponse) ProtoMessage() {}

func (x *GetValueToCacheUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueToCacheUserResponse.ProtoReflect.Descriptor instead.
func (*GetValueToCacheUserResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *GetValueToCacheUserResponse) GetCacheValue() string {
	if x != nil {
		return x.CacheValue
	}
	return ""
}

var File_cache_monitor_proto protoreflect.FileDescriptor

var file_cache_monitor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2d, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x1e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x20,
	0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x70,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x55, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x14, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x41, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x40, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x6f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x4b, 0x65, 0x79, 0x22, 0x3d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54,
	0x6f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0xee, 0x03, 0x0a, 0x13, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4b,
	0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x54, 0x6f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x6f, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x6f,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x2e, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2d, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cache_monitor_proto_rawDescOnce sync.Once
	file_cache_monitor_proto_rawDescData = file_cache_monitor_proto_rawDesc
)

func file_cache_monitor_proto_rawDescGZIP() []byte {
	file_cache_monitor_proto_rawDescOnce.Do(func() {
		file_cache_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_cache_monitor_proto_rawDescData)
	})
	return file_cache_monitor_proto_rawDescData
}

var file_cache_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cache_monitor_proto_goTypes = []any{
	(*GetCacheUserAddressListRequest)(nil),  // 0: user.GetCacheUserAddressListRequest
	(*GetCacheUserAddressListResponse)(nil), // 1: user.GetCacheUserAddressListResponse
	(*GetCacheUserAppNameListRequest)(nil),  // 2: user.GetCacheUserAppNameListRequest
	(*GetCacheUserAppNameListResponse)(nil), // 3: user.GetCacheUserAppNameListResponse
	(*GetCacheNameListRequest)(nil),         // 4: user.GetCacheNameListRequest
	(*GetCacheNameListResponse)(nil),        // 5: user.GetCacheNameListResponse
	(*GetCacheKeyListRequest)(nil),          // 6: user.GetCacheKeyListRequest
	(*GetCacheKeyListResponse)(nil),         // 7: user.GetCacheKeyListResponse
	(*GetValueToCacheUserRequest)(nil),      // 8: user.GetValueToCacheUserRequest
	(*GetValueToCacheUserResponse)(nil),     // 9: user.GetValueToCacheUserResponse
}
var file_cache_monitor_proto_depIdxs = []int32{
	0, // 0: user.CacheMonitorService.GetCacheUserAddressList:input_type -> user.GetCacheUserAddressListRequest
	2, // 1: user.CacheMonitorService.GetCacheUserAppNameList:input_type -> user.GetCacheUserAppNameListRequest
	4, // 2: user.CacheMonitorService.GetCacheNameList:input_type -> user.GetCacheNameListRequest
	6, // 3: user.CacheMonitorService.GetCacheKeyList:input_type -> user.GetCacheKeyListRequest
	8, // 4: user.CacheMonitorService.GetValueToCacheUser:input_type -> user.GetValueToCacheUserRequest
	1, // 5: user.CacheMonitorService.GetCacheUserAddressList:output_type -> user.GetCacheUserAddressListResponse
	3, // 6: user.CacheMonitorService.GetCacheUserAppNameList:output_type -> user.GetCacheUserAppNameListResponse
	5, // 7: user.CacheMonitorService.GetCacheNameList:output_type -> user.GetCacheNameListResponse
	7, // 8: user.CacheMonitorService.GetCacheKeyList:output_type -> user.GetCacheKeyListResponse
	9, // 9: user.CacheMonitorService.GetValueToCacheUser:output_type -> user.GetValueToCacheUserResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_monitor_proto_init() }
func file_cache_monitor_proto_init() {
	if File_cache_monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cache_monitor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserAddressListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserAddressListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserAppNameListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserAppNameListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheNameListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheNameListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheKeyListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheKeyListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetValueToCacheUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetValueToCacheUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cache_monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_monitor_proto_goTypes,
		DependencyIndexes: file_cache_monitor_proto_depIdxs,
		MessageInfos:      file_cache_monitor_proto_msgTypes,
	}.Build()
	File_cache_monitor_proto = out.File
	file_cache_monitor_proto_rawDesc = nil
	file_cache_monitor_proto_goTypes = nil
	file_cache_monitor_proto_depIdxs = nil
}
