// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.3
// source: cache-monitor.proto

package cache_monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCacheUserIpListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
}

func (x *GetCacheUserIpListRequest) Reset() {
	*x = GetCacheUserIpListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserIpListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserIpListRequest) ProtoMessage() {}

func (x *GetCacheUserIpListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserIpListRequest.ProtoReflect.Descriptor instead.
func (*GetCacheUserIpListRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *GetCacheUserIpListRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type GetCacheUserIpListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCacheIpList []string `protobuf:"bytes,1,rep,name=UserCacheIpList,proto3" json:"UserCacheIpList,omitempty"`
}

func (x *GetCacheUserIpListResponse) Reset() {
	*x = GetCacheUserIpListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserIpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserIpListResponse) ProtoMessage() {}

func (x *GetCacheUserIpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserIpListResponse.ProtoReflect.Descriptor instead.
func (*GetCacheUserIpListResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *GetCacheUserIpListResponse) GetUserCacheIpList() []string {
	if x != nil {
		return x.UserCacheIpList
	}
	return nil
}

type GetCacheUserAppNameListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCacheUserAppNameListRequest) Reset() {
	*x = GetCacheUserAppNameListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserAppNameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserAppNameListRequest) ProtoMessage() {}

func (x *GetCacheUserAppNameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserAppNameListRequest.ProtoReflect.Descriptor instead.
func (*GetCacheUserAppNameListRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{2}
}

type GetCacheUserAppNameListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCacheAppNameList []string `protobuf:"bytes,1,rep,name=UserCacheAppNameList,proto3" json:"UserCacheAppNameList,omitempty"`
}

func (x *GetCacheUserAppNameListResponse) Reset() {
	*x = GetCacheUserAppNameListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheUserAppNameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheUserAppNameListResponse) ProtoMessage() {}

func (x *GetCacheUserAppNameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheUserAppNameListResponse.ProtoReflect.Descriptor instead.
func (*GetCacheUserAppNameListResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *GetCacheUserAppNameListResponse) GetUserCacheAppNameList() []string {
	if x != nil {
		return x.UserCacheAppNameList
	}
	return nil
}

type GetCacheNameListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
}

func (x *GetCacheNameListRequest) Reset() {
	*x = GetCacheNameListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheNameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheNameListRequest) ProtoMessage() {}

func (x *GetCacheNameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheNameListRequest.ProtoReflect.Descriptor instead.
func (*GetCacheNameListRequest) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *GetCacheNameListRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type GetCacheNameListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheNameList []string `protobuf:"bytes,1,rep,name=CacheNameList,proto3" json:"CacheNameList,omitempty"`
}

func (x *GetCacheNameListResponse) Reset() {
	*x = GetCacheNameListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_monitor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheNameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheNameListResponse) ProtoMessage() {}

func (x *GetCacheNameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_monitor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheNameListResponse.ProtoReflect.Descriptor instead.
func (*GetCacheNameListResponse) Descriptor() ([]byte, []int) {
	return file_cache_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *GetCacheNameListResponse) GetCacheNameList() []string {
	if x != nil {
		return x.CacheNameList
	}
	return nil
}

var File_cache_monitor_proto protoreflect.FileDescriptor

var file_cache_monitor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2d, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x46, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x49, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x49, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x1f,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x41, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x33, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xaf, 0x02, 0x0a, 0x13, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x59, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x70, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19,
	0x2e, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2d, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cache_monitor_proto_rawDescOnce sync.Once
	file_cache_monitor_proto_rawDescData = file_cache_monitor_proto_rawDesc
)

func file_cache_monitor_proto_rawDescGZIP() []byte {
	file_cache_monitor_proto_rawDescOnce.Do(func() {
		file_cache_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_cache_monitor_proto_rawDescData)
	})
	return file_cache_monitor_proto_rawDescData
}

var file_cache_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cache_monitor_proto_goTypes = []any{
	(*GetCacheUserIpListRequest)(nil),       // 0: user.GetCacheUserIpListRequest
	(*GetCacheUserIpListResponse)(nil),      // 1: user.GetCacheUserIpListResponse
	(*GetCacheUserAppNameListRequest)(nil),  // 2: user.GetCacheUserAppNameListRequest
	(*GetCacheUserAppNameListResponse)(nil), // 3: user.GetCacheUserAppNameListResponse
	(*GetCacheNameListRequest)(nil),         // 4: user.GetCacheNameListRequest
	(*GetCacheNameListResponse)(nil),        // 5: user.GetCacheNameListResponse
}
var file_cache_monitor_proto_depIdxs = []int32{
	0, // 0: user.CacheMonitorService.GetCacheUserIpList:input_type -> user.GetCacheUserIpListRequest
	2, // 1: user.CacheMonitorService.GetCacheUserAppNameList:input_type -> user.GetCacheUserAppNameListRequest
	4, // 2: user.CacheMonitorService.GetCacheNameList:input_type -> user.GetCacheNameListRequest
	1, // 3: user.CacheMonitorService.GetCacheUserIpList:output_type -> user.GetCacheUserIpListResponse
	3, // 4: user.CacheMonitorService.GetCacheUserAppNameList:output_type -> user.GetCacheUserAppNameListResponse
	5, // 5: user.CacheMonitorService.GetCacheNameList:output_type -> user.GetCacheNameListResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_monitor_proto_init() }
func file_cache_monitor_proto_init() {
	if File_cache_monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cache_monitor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserIpListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserIpListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserAppNameListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheUserAppNameListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheNameListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_monitor_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetCacheNameListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cache_monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_monitor_proto_goTypes,
		DependencyIndexes: file_cache_monitor_proto_depIdxs,
		MessageInfos:      file_cache_monitor_proto_msgTypes,
	}.Build()
	File_cache_monitor_proto = out.File
	file_cache_monitor_proto_rawDesc = nil
	file_cache_monitor_proto_goTypes = nil
	file_cache_monitor_proto_depIdxs = nil
}
