port: 9090
database:
  data_source_name: 123123
  gorm_cfg:
    skip_default_transaction: false
    query_fields: true
  max_open_connections: 100
  # unit: milliseconds, 3600000ms = 1hour
  connection_max_lifetime: 3600000
debug: true