port: 9099
database:
  data_source_name: root:root@tcp(localhost:3307)/ocean?charset=utf8&parseTime=True&loc=Local
  gorm_cfg:
    skip_default_transaction: false
    query_fields: true
  max_open_connections: 100
  # unit: milliseconds, 3600000ms = 1hour
  connection_max_lifetime: 3600000
debug: true
ginMode: debug