// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import ()

// Injectors from wire.go:

// InitServices 初始化所有服务
func InitServices() *Services {
	return &Services{}
}
