// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	callingLogic "visual-state-machine/internal/logic/calling"
	callingRepo "visual-state-machine/internal/repo/log"
	callingsvc "visual-state-machine/internal/service/flow"
)

// Injectors from wire.go:

// InitServices 初始化所有服务
func InitServices() *Services {
	callingApi:=callingRepo.New()
	callingLogic:=callingLogic.New(callingApi)
	callingService :=callingsvc.NewTestService(callingLogic)
	services := newServices(callingService)
	return services
}
